//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealWatcher.Models
{
    public partial class Configuration
    {
        public string Key { get; set; }
        public int TypeId { get; set; }
        public byte[] Value { get; set; }
        public int Id { get; set; }
    
        public virtual ConfigurationValueType ConfigurationValueType { get; set; }
    }
}
