//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DealWatcher.Models
{
    public partial class PriceCacheDuration
    {
        public int SellerId { get; set; }
        public TimeSpan CacheLifetme { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
