
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DealWatcher.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductCodeType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductCodeType()
    {

        this.ProductCodes = new HashSet<ProductCode>();

    }


    public int Id { get; set; }

    public string Type { get; set; }

    public Nullable<int> ProprietarySellerId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductCode> ProductCodes { get; set; }

    public virtual Seller Seller { get; set; }

}

}
